version: '3.8'

services:
  traefik:
    image: traefik:v3.3
    container_name: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik/acme.json:/acme.json:rw
      - ./traefik/traefik.toml:/etc/traefik/traefik.toml:ro
    command:
      - "--api=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedByDefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=your-email@domain.com"
      - "--certificatesresolvers.myresolver.acme.storage=/acme.json"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--providers.docker.network=app-net"
      - "--log.level=INFO"
      - "--accesslog=true"
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "--tries=1", "http://localhost:80/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s
    deploy:
      resources:
        limits:
          memory: 256M

  db1:
    image: postgres:15
    container_name: db1
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=auth_db
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-net
    volumes:
      - pgdata1:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1G
    command: postgres -c max_connections=200 -c shared_buffers=256MB

  db2:
    image: postgres:15
    container_name: db2
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=posting_db
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-net
    volumes:
      - pgdata2:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          memory: 1G
    command: postgres -c max_connections=200 -c shared_buffers=256MB

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    restart: always
    expose:
      - "5672"
      - "15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USERNAME}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-net
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq
    deploy:
      resources:
        limits:
          memory: 512M

  auth-service:
    image: ${DOCKER_REGISTRY}/auth-service:${IMAGE_TAG:-latest}
    container_name: auth-service
    restart: always
    expose:
      - "8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db1:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT=60000
      - SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE=20
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=INFO
      - SERVER_SERVLET_CONTEXT_PATH=/auth
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=never
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - SERVER_FORWARD_HEADERS_STRATEGY=FRAMEWORK
      - SERVER_USE_FORWARD_HEADERS=true
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      db1:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8081/auth/actuator/health || exit 1"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 120s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.auth-service.rule=PathPrefix(`/auth`)"
      - "traefik.http.routers.auth-service.entrypoints=websecure"
      - "traefik.http.routers.auth-service.tls=true"
      - "traefik.http.routers.auth-service.tls.certresolver=myresolver"
      - "traefik.http.services.auth-service.loadbalancer.server.port=8081"
      - "traefik.http.services.auth-service.loadbalancer.passHostHeader=true"
    networks:
      - app-net
    deploy:
      resources:
        limits:
          memory: 1G

  posting-service:
    image: ${DOCKER_REGISTRY}/posting-service:${IMAGE_TAG:-latest}
    container_name: posting-service
    restart: always
    expose:
      - "8082"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db2:5432/posting_db
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SERVER_SERVLET_CONTEXT_PATH=/posting
      - SERVER_FORWARD_HEADERS_STRATEGY=framework
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION=${JWT_EXPIRATION}
      - LOGGING_LEVEL_ROOT=INFO
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_WEB=INFO
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info
      - MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS=never
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - SPRING_RABBITMQ_USERNAME=${RABBITMQ_USERNAME}
      - SPRING_RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - REDIS_HOST=redis
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      db2:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "--max-time", "10", "http://localhost:8082/posting/actuator/health"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 120s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.posting-service.rule=PathPrefix(`/posting`)"
      - "traefik.http.routers.posting-service.entrypoints=websecure"
      - "traefik.http.routers.posting-service.tls=true"
      - "traefik.http.routers.posting-service.tls.certresolver=myresolver"
      - "traefik.http.services.posting-service.loadbalancer.server.port=8082"
    networks:
      - app-net
    deploy:
      resources:
        limits:
          memory: 1G

  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    expose:
      - "6379"
    networks:
      - app-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    volumes:
      - redisdata:/data
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    deploy:
      resources:
        limits:
          memory: 384M

  style-bridge-fe:
    image: ${DOCKER_REGISTRY}/style-bridge-fe:${IMAGE_TAG:-latest}
    container_name: style-bridge-fe
    restart: always
    expose:
      - "80"
    depends_on:
      auth-service:
        condition: service_healthy
      posting-service:
        condition: service_healthy
    environment:
      - API_URL=https://truongvinhkhuong.io.vn
      - AUTH_API_PATH=/auth
      - POSTING_API_PATH=/posting
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=app-net"
      - "traefik.http.routers.frontend.rule=PathPrefix(`/`)"
      - "traefik.http.routers.frontend.priority=1"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    networks:
      - app-net
    deploy:
      resources:
        limits:
          memory: 256M

networks:
  app-net:
    driver: bridge

volumes:
  pgdata1:
  pgdata2:
  rabbitmqdata:
  redisdata: 